<style>
    .blog{
        line-height: 50px;
        margin: 50px;
    }
</style>

<template>
    <ul class="blog">
        <li><a href="#blog-flow">seekJs 加载流程图</a></li>
        <li><a href="#blog-view-flow">seekjs-view 流程图</a></li>
    </ul>
</template>

<script>
    exports.subpage = "blog-flow";
    exports.changePage = function(){
        this.subpage = this.element.innerHTML;
        this.render();
    };
</script>